apiVersion: v1
kind: Service
metadata:
  name: werwerfood-service
spec:
  selector:
    app: werwerfood
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30006
  type: NodePort
